### PR TITLE
Correct the range for modulo

### PR DESCRIPTION
**Pull request by linD026**
The value `N` is power of 2 integer which is declared in :
```cpp
#define N (1 << 12) /* node size */
#define NBITS (N - 1)
```
`N` will become  `1 0000 0000 0000` in binary.
When the divisor `N` is power of 2, the operator `%` is equal to logical AND with `N - 1`
which means that  i mod 2^n with bitwise AND is ( i & N - 1 ) not ( i & N ).

For example: 
`3 % 4 == 3 == 0011 % 0100 == 0011 & ( 0100 - 1 )`

### CODE REVIEW

**Review by jserv — CHANGES_REQUESTED** [review]
Squash the commits and force-push.

**Review by jserv — CHANGES_REQUESTED** [review]
The subject of both git commit and this pull request was weird. Improve the description.
Also, fix the merge conflicts.

**Comment by linD026** [comment]
Fixed the commit.
The merge still conflicting?

**Comment by jserv** [comment]
> Fixed the commit.
> The merge still conflicting?

No conflict so far. Then, make the subject informative.

**Comment by jserv** [comment]
The subject can be as following:
> Correct the range for modulo

Meanwhile, avoid using [grave accent](https://en.wikipedia.org/wiki/Grave_accent) in commit messages. We always expect the plain text without markdown syntax.

**Comment by jserv** [comment]
@linD026, Thanks for contributing! I made small changes against this commit.

**Pull request merged**
