### PR TITLE
Rename ringbuf-shm to ringbuf_shm

### PR DESCRIPTION
**Pull request by ChunMinChang**
The `ringbuf_shm` link in README.md is not working since it's linked to
an inexistent `ringbuf_shm` folder. Renaming `ringbuf-shm` folder to
`ringbuf_shm` fixes the problem.

### CODE REVIEW

**Comment by jserv** [comment]
Why didn't change the top-level `README.md` instead?

**Comment by ChunMinChang** [comment]
I am comfortable with both approaches as long as they can fix the link.

The term in [ringbuf-shm/README.md](https://github.com/sysprog21/concurrent-programs/blob/381b798505fa58810f7fc1882d22a12bbe17d365/ringbuf-shm/README.md#ringbuf_shm) is named `ringbuf_shm` instead, and the `_` is used in another folder's name (`preempt_sched`), so I guess the naming convention here prefers `_`.

I didn't file the PR in the first place because I'd like to keep the author's name on the files (in git blame and history). So renaming the folder's name in `README.md` rather than the folder's name itself is probably more in line with my need.

Feel free to let me know what works for you best.

**Comment by jserv** [comment]
> The term in [ringbuf-shm/README.md](https://github.com/sysprog21/concurrent-programs/blob/381b798505fa58810f7fc1882d22a12bbe17d365/ringbuf-shm/README.md#ringbuf_shm) is named `ringbuf_shm` instead, and the `_` is used in another folder's name (`preempt_sched`), so I guess the naming convention here prefers `_`.

I did not follow a consistent name scheme since these programs were written separately. The minimal change is fine to me.

**Comment by jserv** [comment]
Thank @ChunMinChang for contributing!

**Pull request merged**
